# Change this to your GitHub username
owner: Kyo1685

# Change this to the name of your repository
repo: supabase-monitoring

sites:
  - name: Render
    url: https://supabase.com
  - name: My Personal App
    url: https://supabase.com/dashboard/project/kaphkcyzqlemozeszdyd

# This section creates your status page
status-website:
  # This line is important! It tells the status page where to find its files.
  baseUrl: /supabase-monitoring
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: My Uptime Status
  introTitle: "This is a live status page for my services."
  introMessage: "It uses GitHub Actions to check my sites every 5 minutes."
  navbar:
    - title: Status
      url: /
    - title: GitHub
      url: https://github.com/Kyo1685/supabase-monitoring

workflowSchedule:
  graphs: "0 0 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  uptime: "*/5 * * * *"

# --- TELEGRAM NOTIFICATION SECTION ---
# This block tells Upptime to send alerts to Telegram
notifications:
  - type: telegram
    # NOTE: The actual Bot Token and Chat ID are loaded from your GitHub Secrets.
    message: '🚨 $EMOJI $SITE_NAME ($SITE_URL) is $STATUS! Check the issue here: $ISSUE_URL'


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
